/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'subsubra' at '5/30/17 12:44 PM' with Gradle 2.14.1
 *
 * @author subsubra, @date 5/30/17 12:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
